name: "Plume"
services:
    database:
        image: mariadb
        ports:
            - "3306:3306"
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mariadb_data:/var/lib/mysql

volumes:
    mariadb_data: {}
