-- Your SQL goes here
CREATE TABLE User 
(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    banner VARCHAR(400) NOT NULL
);

CREATE TABLE Messages
(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    author VARCHAR(100) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    message_content VARCHAR(10000) NOT NULL
);

CREATE TABLE Autorization
(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_id INT NOT NULL,
    token VARCHAR(200) NOT NULL,
    type VARCHAR(50) NOT NULL
)